# Generated by Django 4.0.5 on 2022-06-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('link_to', models.URLField(blank=True, null=True)),
                ('link_str', models.CharField(blank=True, max_length=200, null=True)),
                ('date_published', models.DateField()),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_image', models.ImageField(upload_to='images/')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.publication')),
            ],
        ),
    ]
