# Generated by Django 4.0.5 on 2022-06-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_publication_publicationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationimage',
            name='publication_image',
            field=models.ImageField(upload_to='C:\\Users\\RAMZI\\projet_django\\emma\\src\\webapp\\images/publication_images'),
        ),
    ]
