# Generated by Django 4.0.5 on 2022-06-08 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_publicationimage_publication_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationimage',
            name='publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='photo_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.publicationimage'),
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='publication_image',
            field=models.ImageField(upload_to='C:\\Users\\RAMZI\\projet_django\\Emma\\src\\webapp\\static/images/publication_images'),
        ),
    ]
