# Generated by Django 4.0.5 on 2022-06-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_publicationimage_publication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationimage',
            old_name='publication_image',
            new_name='photo_url',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='publicationimage',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.publicationimage'),
        ),
    ]
