# Generated by Django 4.0.5 on 2022-06-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_publication_image_publicationimage_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationimage',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.publication'),
        ),
    ]
