# Generated by Django 4.0.5 on 2022-06-09 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_livre_alter_publicationimage_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('card_image', models.CharField(max_length=255)),
                ('card_description', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Présentation',
                'verbose_name_plural': 'Présentation',
            },
        ),
        migrations.AlterModelOptions(
            name='livre',
            options={'verbose_name': "livre d'or", 'verbose_name_plural': "livre d'or"},
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 11, 23, 29, 358340)),
        ),
    ]
