# Generated by Django 4.0.5 on 2022-06-09 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_presentation_alter_livre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('card_image', models.CharField(max_length=255)),
                ('card_description', models.TextField()),
            ],
            options={
                'verbose_name': 'PrésentationCard',
                'verbose_name_plural': 'PrésentationCards',
            },
        ),
        migrations.CreateModel(
            name='Présentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_one', models.TextField()),
                ('description_two', models.TextField()),
                ('adresse', models.TextField()),
            ],
            options={
                'verbose_name': 'Présentation',
                'verbose_name_plural': 'Présentations',
            },
        ),
        migrations.DeleteModel(
            name='Presentation',
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 11, 31, 32, 737225)),
        ),
    ]
