# Generated by Django 4.0.5 on 2022-06-09 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_presentationcard_présentation_delete_presentation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Présentation',
            new_name='Presentation',
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Presentation', 'verbose_name_plural': 'Presentations'},
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 11, 32, 32, 312028)),
        ),
    ]
