# Generated by Django 4.0.5 on 2022-06-09 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_rename_présentation_presentation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 13, 24, 41, 540286)),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
