# Generated by Django 4.0.5 on 2022-06-09 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_galeries_alter_livre_date_update_galeriesimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 17, 29, 9, 957558)),
        ),
    ]
