# Generated by Django 4.0.5 on 2022-06-09 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_livre_date_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriesimage',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='galeries',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\RAMZI\\projet_django\\Emma\\src\\webapp\\static/images/galeries_images'),
        ),
        migrations.AddField(
            model_name='galeriesimage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\RAMZI\\projet_django\\Emma\\src\\webapp\\static/images/galeries_images'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 18, 35, 17, 917848)),
        ),
    ]
